"""Request / response models for the ``action`` HTTP API.

The request body is a union discriminated by ``type`` — one model per kind of
event, so each kind validates only the fields it needs. Adding a kind of event
means adding a model here and to :data:`CareEventCreate`.
"""

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CareEventType(StrEnum):
    ACTION_COMPLETED = "action_completed"
    WATERED = "watered"


#: ``companion``'s ``care_plan.actions[].type``.
ActionType = Literal["water", "move", "inspect", "other"]

_Id = Annotated[str, Field(min_length=1, max_length=64)]


class _CareEventBase(BaseModel):
    #: When the owner did it. Defaults to the time the server receives it.
    occurred_at: AwareDatetime | None = None
    #: Generated by the GUI per button press (e.g. a UUID). Resending the same
    #: value for the same plant returns the event already recorded.
    client_event_id: _Id | None = None
    details: dict[str, Any] | None = None


class ActionCompletedCreate(_CareEventBase):
    """A step of a care plan was marked done."""

    type: Literal[CareEventType.ACTION_COMPLETED]
    care_plan_id: _Id
    action_id: _Id
    action_type: ActionType | None = None


class WateredCreate(_CareEventBase):
    """The plant was watered — with or without a care plan on screen."""

    type: Literal[CareEventType.WATERED]
    #: Set when pressed from a care card; ``None`` for the everyday button.
    care_plan_id: _Id | None = None


CareEventCreate = Annotated[ActionCompletedCreate | WateredCreate, Field(discriminator="type")]


class CareEventRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    plant_id: uuid.UUID
    event_type: CareEventType
    care_plan_id: str | None
    action_id: str | None
    action_type: str | None
    details: dict[str, Any] | None
    occurred_at: datetime
    recorded_at: datetime
    recorded_by_user_id: uuid.UUID | None
    recorded_by_device_id: uuid.UUID | None
    client_event_id: str | None
